// =============================================================================
// HYDRA-UMC-SDK - Rust reference client: hand-written contract types
// Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
// GPL-3.0-or-later - see LICENSE
// =============================================================================

//! Hand-written Rust types for the HYDRA-UMC-SDK v1 contracts, one struct
//! per `contracts/json-schema/v1/*.schema.json` file. These are NOT
//! generated by a tool - written directly from each schema's own
//! `required`/`properties`, the same way `clients/go/types.go` and
//! `clients/typescript/src/types.ts` are for Go and TypeScript. The JSON
//! Schema files remain the normative source; `tests/schema_drift.rs`
//! proves this crate's vendored schema copies stay byte-identical to
//! `contracts/json-schema/v1/`.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// The only `schema_version` value every v1 contract accepts.
pub const SCHEMA_VERSION: &str = "1.0";

/// `device-descriptor.schema.json`
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DeviceDescriptor {
    pub schema_version: String,
    pub node_id: String,
    pub profile: String,
    pub hostname: String,
    pub machine: String,
    pub operating_system: String,
    pub kernel: String,
    pub interfaces: Vec<String>,
    /// `additionalProperties: true` in the schema - unknown fields round-trip
    /// instead of being silently dropped.
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

/// `health-report.schema.json` "state" enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HealthState {
    #[serde(rename = "READY")]
    Ready,
    #[serde(rename = "DEGRADED")]
    Degraded,
    #[serde(rename = "INHIBITED")]
    Inhibited,
    #[serde(rename = "FAULT")]
    Fault,
    #[serde(rename = "SAFE_STOP")]
    SafeStop,
}

/// `health-report.schema.json`
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HealthReport {
    pub schema_version: String,
    pub state: HealthState,
    pub timestamp_utc: String,
    pub checks: serde_json::Map<String, serde_json::Value>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

/// `safety-state.schema.json` "state" enum - narrower than [`HealthState`]
/// (no `Degraded`), matching the real schema and
/// `docs/PYTHON_CLIENT.md`'s own documented distinction between the two.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SafetyStateValue {
    #[serde(rename = "READY")]
    Ready,
    #[serde(rename = "INHIBITED")]
    Inhibited,
    #[serde(rename = "FAULT")]
    Fault,
    #[serde(rename = "SAFE_STOP")]
    SafeStop,
}

/// `safety-state.schema.json`
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SafetyState {
    pub schema_version: String,
    pub state: SafetyStateValue,
    pub source: String,
    pub timestamp_utc: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

/// `update-manifest.schema.json`
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct UpdateManifest {
    pub schema_version: String,
    pub project: String,
    pub version: String,
    pub artifact_url: String,
    pub sha256: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

/// `event-envelope.schema.json`
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EventEnvelope {
    pub schema_version: String,
    pub event_id: String,
    #[serde(rename = "type")]
    pub event_type: String,
    pub source: String,
    pub timestamp_utc: String,
    pub sequence: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

/// `server-discovery.schema.json` - deliberately camelCase field names, the
/// real `GET /api/hydra-info` wire shape (see `docs/CONTRACTS.md`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ServerDiscovery {
    pub schema_version: String,
    pub product: String,
    #[serde(rename = "remoteApiVersion")]
    pub remote_api_version: u64,
    #[serde(rename = "appVersion")]
    pub app_version: String,
    pub hostname: String,
    #[serde(rename = "controllerCount")]
    pub controller_count: u64,
    #[serde(rename = "robotCount")]
    pub robot_count: u64,
    #[serde(rename = "uptimeSeconds")]
    pub uptime_seconds: u64,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

/// `project-manifest.schema.json` "role" enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ProjectManifestRole {
    Api,
    Ui,
    Cli,
    Firmware,
    Library,
    Service,
    Tool,
}

/// `project-manifest.schema.json` "deployment_target" enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProjectManifestDeploymentTarget {
    #[serde(rename = "cm5")]
    Cm5,
    #[serde(rename = "user-pc")]
    UserPc,
    #[serde(rename = "mobile")]
    Mobile,
    #[serde(rename = "wearable")]
    Wearable,
}

/// `project-manifest.schema.json` "maturity" enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ProjectManifestMaturity {
    Scaffolding,
    Functional,
    Established,
    Production,
}

/// `native_version.pattern`'s object form: one regular expression per
/// version component.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NativeVersionPatternComponents {
    pub major: String,
    pub minor: String,
    pub patch: String,
}

/// `project-manifest.schema.json`'s `native_version.pattern` is a real
/// `oneOf`: either a single non-empty regex string, or an object with
/// exactly major/minor/patch regex strings. `#[serde(untagged)]` tries
/// each variant in declaration order, so this round-trips either shape
/// without inventing a field the schema does not have.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NativeVersionPattern {
    Single(String),
    Components(NativeVersionPatternComponents),
}

/// `project-manifest.schema.json`'s `native_version`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NativeVersion {
    pub file: String,
    pub pattern: NativeVersionPattern,
}

/// `project-manifest.schema.json` - the `hydra-umc.project.json` contract
/// every repository in this ecosystem publishes. Unlike the other 6
/// contracts this schema sets `additionalProperties: false`, so this
/// struct has no `extra` field: an unknown field is a real schema
/// violation for this one contract, not an allowed extension - and
/// `#[serde(deny_unknown_fields)]` enforces that at the Rust decoding
/// layer too, not only at the JSON Schema validation layer.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProjectManifest {
    pub schema_version: String,
    pub ecosystem: String,
    pub name: String,
    pub version: String,
    pub role: ProjectManifestRole,
    pub stack: String,
    pub technologies: Vec<String>,
    pub deployment_target: ProjectManifestDeploymentTarget,
    pub maturity: ProjectManifestMaturity,
    pub family: String,
    pub parent: Option<String>,
    pub native_version: NativeVersion,
    pub build: String,
    pub notes: String,
}

/// One entry of `manifest.json`'s `"contracts"` array: a published schema
/// file's name and its sha256 digest.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContractManifestEntry {
    pub file: String,
    pub sha256: String,
}

/// `contracts/json-schema/v1/manifest.json` - the generated integrity
/// manifest listing every published v1 schema file and its sha256 digest
/// (see `contracts/generate_manifest.py`). It is data, not itself a JSON
/// Schema, so it has no schema-based `validate()` entry point;
/// [`crate::verify_contract_manifest`] instead recomputes each listed
/// file's digest and compares it for real.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContractManifest {
    pub schema_version: String,
    pub contracts: Vec<ContractManifestEntry>,
}
