// =============================================================================
// HYDRA-UMC-SDK - TypeScript reference client: hand-written contract types
// Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
// GPL-3.0-or-later - see LICENSE
// =============================================================================

/**
 * Hand-written TypeScript types for the HYDRA-UMC-SDK v1 contracts, one
 * interface per `contracts/json-schema/v1/*.schema.json` file. These are
 * NOT generated by a tool (no `json-schema-to-typescript`/`quicktype` run)
 * - they are written directly from each schema's own `required`/
 * `properties`, the same way `clients/go/types.go` is. The JSON Schema
 * files remain the normative source; `tests/schema-drift.test.ts` proves
 * this package's vendored schema copies stay byte-identical to
 * `contracts/json-schema/v1/`, and `tests/validation.test.ts` proves every
 * real conformance fixture is judged the way its own filename claims.
 */

/** The only schema_version value every v1 contract accepts. */
export const SCHEMA_VERSION = "1.0" as const;

/** device-descriptor.schema.json */
export interface DeviceDescriptor {
  schema_version: "1.0";
  node_id: string;
  profile: string;
  hostname: string;
  machine: string;
  operating_system: string;
  kernel: string;
  interfaces: string[];
  [extra: string]: unknown;
}

/** health-report.schema.json "state" enum. */
export type HealthState = "READY" | "DEGRADED" | "INHIBITED" | "FAULT" | "SAFE_STOP";

/** health-report.schema.json */
export interface HealthReport {
  schema_version: "1.0";
  state: HealthState;
  timestamp_utc: string;
  checks: Record<string, unknown>;
  [extra: string]: unknown;
}

/**
 * safety-state.schema.json "state" enum - narrower than HealthState (no
 * DEGRADED), matching the real schema and docs/PYTHON_CLIENT.md's own
 * documented distinction between the two.
 */
export type SafetyStateValue = "READY" | "INHIBITED" | "FAULT" | "SAFE_STOP";

/** safety-state.schema.json */
export interface SafetyState {
  schema_version: "1.0";
  state: SafetyStateValue;
  source: string;
  timestamp_utc: string;
  [extra: string]: unknown;
}

/** update-manifest.schema.json */
export interface UpdateManifest {
  schema_version: "1.0";
  project: string;
  version: string;
  artifact_url: string;
  sha256: string;
  [extra: string]: unknown;
}

/** event-envelope.schema.json */
export interface EventEnvelope {
  schema_version: "1.0";
  event_id: string;
  type: string;
  source: string;
  timestamp_utc: string;
  sequence: number;
  correlation_id?: string;
  [extra: string]: unknown;
}

/**
 * server-discovery.schema.json - deliberately camelCase field names, the
 * real GET /api/hydra-info wire shape (see docs/CONTRACTS.md).
 */
export interface ServerDiscovery {
  schema_version: "1.0";
  product: string;
  remoteApiVersion: number;
  appVersion: string;
  hostname: string;
  controllerCount: number;
  robotCount: number;
  uptimeSeconds: number;
  [extra: string]: unknown;
}

/** project-manifest.schema.json "role" enum. */
export type ProjectManifestRole = "api" | "ui" | "cli" | "firmware" | "library" | "service" | "tool";

/** project-manifest.schema.json "deployment_target" enum. */
export type ProjectManifestDeploymentTarget = "cm5" | "user-pc" | "mobile" | "wearable";

/** project-manifest.schema.json "maturity" enum. */
export type ProjectManifestMaturity = "scaffolding" | "functional" | "established" | "production";

/**
 * project-manifest.schema.json's native_version.pattern is a real
 * `oneOf`: either a single non-empty regex string, or an object with
 * exactly major/minor/patch regex strings.
 */
export type NativeVersionPattern = string | { major: string; minor: string; patch: string };

/** project-manifest.schema.json's native_version. */
export interface NativeVersion {
  file: string;
  pattern: NativeVersionPattern;
}

/**
 * project-manifest.schema.json - the hydra-umc.project.json contract every
 * repository in this ecosystem publishes. Unlike the other 6 contracts
 * this schema sets `additionalProperties: false`, so this interface has no
 * index signature: an unknown field is a real schema violation for this
 * one contract, not an allowed extension.
 */
export interface ProjectManifest {
  schema_version: "1.0";
  ecosystem: "HYDRA-UMC";
  name: string;
  version: string;
  role: ProjectManifestRole;
  stack: string;
  technologies: string[];
  deployment_target: ProjectManifestDeploymentTarget;
  maturity: ProjectManifestMaturity;
  family: string;
  parent: string | null;
  native_version: NativeVersion;
  build: string;
  notes: string;
}

/** One entry of manifest.json's "contracts" array. */
export interface ContractManifestEntry {
  file: string;
  sha256: string;
}

/**
 * contracts/json-schema/v1/manifest.json - the generated integrity
 * manifest listing every published v1 schema file and its sha256 digest
 * (see contracts/generate_manifest.py). It is data, not itself a JSON
 * Schema, so it is not one of the contracts `validate()` accepts;
 * `verifyContractManifest()` (manifest.ts) checks it directly instead.
 */
export interface ContractManifest {
  schema_version: "1.0";
  contracts: ContractManifestEntry[];
}

/** The 7 contract names `validate()`/`isValid()` accept. */
export type ContractName =
  | "DeviceDescriptor"
  | "HealthReport"
  | "SafetyState"
  | "UpdateManifest"
  | "EventEnvelope"
  | "ServerDiscovery"
  | "ProjectManifest";
